### ISSUE TITLE
Add like/dislike routes and endpoints

### ISSUE THREAD

**Issue by KeithSantamaria** [KeithSantamaria/Project2-Group1-FlickList#4]
This should be done in the service

The Review object's dislike and like fields should be set to 0 if the Title and Textbody are empty

**Comment by toledojuan** [comment]
To do:
 - Create 2 routes after /reviews eg. /reviews/{id}/incrementLike or /reviews/incrementList/{id}
 - Create 2service functions that check if title and text exists, and then increase likes or dislikes

**Comment by toledojuan** [comment]
No need for this feature, as we can do the same updating a review
